spring:
  resources:
    add-mappings: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates/thymeleaf
    suffix: .html

  datasource:
    username: sbsst
    password: sbs123414
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbs_plus

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        user_sql_comments: true
        format_sql: true
        show_sql: true

  output:
    ansi:
      enabled: always

