server:
  port: 8080

# 이미지 업로드 경로 설정
upload:
#  directory: /users/sechan/upload/sbsplus/img/

  # [사용법] <아래는 윈도우용>
  # 1. 계정명에는 사용자 디렉토리 경로보고 본인 로컬 폴더명 써주세요
  # 2. "C:\Users\계정명\" (사용자)폴더에 가서 upload 폴더 만들고 아래에 sbsplus 폴더 만들고 아래에 img 폴더 만든다.
  directory: C:\Users\정지영\upload\sbsplus\img\


spring:
  resources:
    add-mappings: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates/thymeleaf
    suffix: .html

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbs_plus

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        user_sql_comments: true
        format_sql: true
        show_sql: true

  output:
    ansi:
      enabled: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: sbsplus100
    password: mizvnmxdnshxfghf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true
  freemarker:
    :ache: false